//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardRecord_His
    {
        public int id { get; set; }
        public Nullable<int> StationID { get; set; }
        public int Room { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> ChkTime { get; set; }
        public Nullable<int> time1 { get; set; }
        public Nullable<int> time2 { get; set; }
        public Nullable<int> time3 { get; set; }
        public Nullable<int> time4 { get; set; }
        public Nullable<int> package1 { get; set; }
        public Nullable<int> package2 { get; set; }
        public Nullable<int> yes { get; set; }
        public Nullable<int> no { get; set; }
        public string Pkg { get; set; }
    }
}
