//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardRecord
    {
        public int id { get; set; }
        public Nullable<int> StationID { get; set; }
        public int Room { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> ChkTime { get; set; }
        public Nullable<int> time1 { get; set; }
        public Nullable<int> time2 { get; set; }
        public Nullable<int> time3 { get; set; }
        public Nullable<int> time4 { get; set; }
        public Nullable<int> Package1 { get; set; }
        public Nullable<int> package2 { get; set; }
        public Nullable<int> yes { get; set; }
        public Nullable<int> no { get; set; }
    }
}
