//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fitness24
    {
        public int id { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> Room { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> ChkTime { get; set; }
    }
}
