//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public System.DateTime ActionTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IP { get; set; }
        public string Client { get; set; }
    
        public virtual User Users { get; set; }
    }
}
