//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onecardEntities : DbContext
    {
        public onecardEntities()
            : base("name=onecardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CardRecord> CardRecord { get; set; }
        public DbSet<CardRecord_His> CardRecord_His { get; set; }
        public DbSet<ExFloor_Record> ExFloor_Record { get; set; }
        public DbSet<ExFloor_Record24> ExFloor_Record24 { get; set; }
        public DbSet<Fitness> Fitness { get; set; }
        public DbSet<Fitness24> Fitness24 { get; set; }
        public DbSet<ZaoCanIn> ZaoCanIn { get; set; }
        public DbSet<ZaoCanIn24> ZaoCanIn24 { get; set; }
    }
}
