//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwimmingCard
    {
        public int Id { get; set; }
        public string CardId { get; set; }
        public string CardNumber { get; set; }
        public string UserName { get; set; }
        public string Gender { get; set; }
        public int Count { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ExpiredAt { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
    }
}
