//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZaoCanIn
    {
        public int id { get; set; }
        public int Room { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Vip { get; set; }
        public Nullable<int> Pax { get; set; }
        public string Package { get; set; }
        public string ChineseName { get; set; }
    }
}
